<?php
// This file is generated by Composer
require_once 'vendor/autoload.php';

// List all our repos.
function show_available_repos( $github_user ) {
	$client = new \Github\Client();
	$repositories = $client->api( 'user' )->repositories( $github_user );
	$return = '<dl>';
	foreach ( $repositories as $repository ) :
		$return .= '<dt><a href="?repo=' . $repository['full_name'] . '">' . $repository['name'] . '</a></dt>';
		$return .= '<dd>' . $repository['description'] . '<dd>';
	endforeach;
	$return .= '</dl>';
	echo $return;
	return true;
}

// Select the repo as entered via the URL.
$_REQUEST = array_merge( $_GET, $_POST );
if ( isset( $_REQUEST['repo'] ) ) :
	echo "Here is my repo stuff!";
else : ?>
	<h2>First, choose a project.</h2>
	<?php show_available_repos( 'a8cteam51' ); ?>
<?php endif;
