<?php
	// This file is generated by Composer
	require_once 'vendor/autoload.php';
?>

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">

  <title>SITREP: Your Github project status</title>
  <meta name="description" content="A custom status page for Github projects.">
  <meta name="author" content="@sarahmonster">

  <link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Bowlby+One+SC|Karla|Ultra" rel="stylesheet">
  <link href="style.css" rel="stylesheet">
</head>

<body>
	<div id="page">

	<?php
	// Select the repo as entered via the URL.
	$_REQUEST = array_merge( $_GET, $_POST );

	if ( isset( $_REQUEST['repo'] ) ) :
		// Show us a status page for our project.

		$repo = explode( '/', $_REQUEST['repo'] );

		// Show current milestone.
		include( 'inc/milestones.php' );
		show_current_milestone( $repo[0], $repo[1] );
		show_upcoming_milestones( $repo[0], $repo[1] );

	else :
		// Otherwise, show a list of public repos.
		echo '<h2>First, choose a project.</h2>';
		include( 'inc/repositories.php' );
		show_available_repos( 'a8cteam51' );
	endif; ?>

</div><!-- #page -->

</body>
</html>
