<?php
	// This file is generated by Composer
	require_once 'vendor/autoload.php';

	// This is just some extra common functions.
	include_once 'inc/extra.php';
?>

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">

  <title>SITREP: Your Github project status</title>
  <meta name="description" content="A custom status page for Github projects.">
  <meta name="author" content="@sarahmonster">

  <link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Bowlby+One+SC|Karla|Ultra" rel="stylesheet">
  <link href="style.css" rel="stylesheet">
</head>

<body>
	<div id="page">

	<?php
	// Select the repo as entered via the URL.
	$_REQUEST = array_merge( $_GET, $_POST );

	if ( isset( $_REQUEST['repo'] ) ) :
		// Show us a status page for our project.

		$repo = explode( '/', $_REQUEST['repo'] );

		?>

		<div class="milestones">
			<?php
			// Show current and upcoming milestones.
			include( 'inc/milestones.php' );
			show_current_milestone( $repo[0], $repo[1] );
			show_upcoming_milestones( $repo[0], $repo[1] );
			?>
		</div>

		<div class="activity">
			<?php
			// Show recent activity.
			include( 'inc/activity.php' );
			show_activity_feed( $repo[0], $repo[1] );
			?>
		</div>

		<div class="widget progress">
			<h2 class="widget-title">Progress this week</h2>

			<div class="badge number-commits">
				<span class="big-number">
					<?php number_commits( $repo[0], $repo[1], 'week' ); ?>
				</span>
				<span class="label">commits</span>
			</div>

			<div class="badge issues-opened">
				<span class="big-number">
					<?php number_issues( $repo[0], $repo[1], 'week', 'opened' ); ?>
				</span>
				<span class="label">issues opened</span>
			</div>

			<div class="badge issues-closed">
				<span class="big-number">
					<?php number_issues( $repo[0], $repo[1], 'week', 'closed' ); ?>
				</span>
				<span class="label">issues closed</span>
			</div>

		</div><!-- .widget .progress -->

	<?php else :
		// Otherwise, show a list of public repos.
		echo '<h2>First, choose a project.</h2>';
		include( 'inc/repositories.php' );
		show_available_repos( 'a8cteam51' );
	endif; ?>

</div><!-- #page -->

</body>
</html>
